name: sc_clean_architecture
description: A new Flutter application.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_slidable: ^0.5.7
  flutter_riverpod: ^0.12.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  pedantic: ^1.9.2

flutter:
  uses-material-design: true

  assets:
     - assets/christmas_jan.png
     - assets/wish_list.json
